src/main/java/uk/gov/justice/laa/portal/landingpage/service/LaaAppDetailsStore.java
The CSV file loading worked fine in IDE but failed to load when application was run in isolation. Updated the CVS file loading logic so, it supports loading the file when the application was run as jar.
=> STB-1939 - Updated loading of CSV file

build.gradle, src/main/java/uk/gov/justice/laa/portal/landingpage/service/LaaAppDetailsStore.java
The changes are to bump spring boot version as well as upgrading Azure AD library so these contains no/less critical vulnerabilities.
=> STB-1536 - Bump spring and other library versions 

.github/workflows/zap_dast_daily_dev.yml, .github/workflows/zap_dast_weekly_test.yml
Updated report file names and removed workflow and push from trigger
=> Updated report file names and removed workflow and push from trigger

build.gradle, src/test/java/uk/gov/justice/laa/portal/landingpage/ApplicationTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/config/GraphClientConfigTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/config/SecurityConfigTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/controller/LoginControllerTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/controller/UserControllerTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/LoginServiceTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/utils/RestUtilTest.java
Drafting pull request to see what the build checks flag
=> Stb 1460 increase test coverage 2

src/main/java/uk/gov/justice/laa/portal/landingpage/controller/UserController.java, src/main/java/uk/gov/justice/laa/portal/landingpage/model/PaginatedUsers.java, src/main/java/uk/gov/justice/laa/portal/landingpage/service/UserService.java, src/main/resources/templates/home.html, src/main/resources/templates/layout.html, src/main/resources/templates/users.html, src/test/java/uk/gov/justice/laa/portal/landingpage/controller/UserControllerTest.java
- Added MOJ UX styling to user listing page
- Added front end paging (what was allowed by graph API)
- Added backend logic for paging
- Added link in home page to user listing
- Added bread crumb to go back to home page after 
https://github.com/user-attachments/assets/45e0a16b-3de3-4009-966f-cbd6f18bd696
=> STB 1537 match styling layout of user listing screen with ux

src/main/resources/templates/user/offices.html
Backend controllers for create user journey still need brought across from old repo to view this page.
=> add offices ui

.github/workflows/test-report.yml
Bumping this to match the new coverage (and try to prevent regression)
=> [STB-1460] Increasing test coverage gate to 50%

src/main/java/uk/gov/justice/laa/portal/landingpage/controller/UserController.java, src/main/java/uk/gov/justice/laa/portal/landingpage/service/UserService.java, src/main/resources/templates/home.html, src/main/resources/templates/manage-user.html, src/main/resources/templates/users.html, src/test/java/uk/gov/justice/laa/portal/landingpage/controller/UserControllerTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/UserServiceTest.java
- Updated user link to route to the new manage-user page
- Added new template for managing user details and displaying associated data
- Adjusted layout configuration by removing the feedback element
- Cleaned up imports and added a method to fetch and format the user's last logged in date
- Added a new endpoint to render the manage-user page with user details
- Added tests coverage for new getLastLoggedInByUserId method
https://github.com/user-attachments/assets/31e1c590-1ee9-4dc0-b505-725cd3b0bc01
=> Stb 1617 UI view user details screen

src/main/java/uk/gov/justice/laa/portal/landingpage/entity/BaseEntity.java, src/main/java/uk/gov/justice/laa/portal/landingpage/entity/EntraAppRegistration.java, src/main/java/uk/gov/justice/laa/portal/landingpage/entity/EntraUser.java, src/main/java/uk/gov/justice/laa/portal/landingpage/entity/Firm.java, src/main/java/uk/gov/justice/laa/portal/landingpage/entity/FirmType.java, src/main/java/uk/gov/justice/laa/portal/landingpage/entity/LaaApp.java, src/main/java/uk/gov/justice/laa/portal/landingpage/entity/LaaAppRole.java, src/main/java/uk/gov/justice/laa/portal/landingpage/entity/LaaUserProfile.java, src/main/java/uk/gov/justice/laa/portal/landingpage/entity/Office.java, src/main/java/uk/gov/justice/laa/portal/landingpage/entity/UserType.java, src/main/java/uk/gov/justice/laa/portal/landingpage/repository/EntraAppRegistrationRepository.java, src/main/java/uk/gov/justice/laa/portal/landingpage/repository/EntraUserRepository.java, src/main/java/uk/gov/justice/laa/portal/landingpage/repository/FirmRepository.java, src/main/java/uk/gov/justice/laa/portal/landingpage/repository/LaaAppRepository.java, src/main/java/uk/gov/justice/laa/portal/landingpage/repository/LaaAppRoleRepository.java, src/main/java/uk/gov/justice/laa/portal/landingpage/repository/LaaUserProfileRepository.java, src/main/java/uk/gov/justice/laa/portal/landingpage/repository/OfficeRepository.java
Initial Version of Data Model for LAA
The table creation queries generated by Hibernate are
```
create table entra_app_registration (entra_app_registration_id uuid not null, app_registration_name varchar(255) not null, primary key (entra_app_registration_id))
create table entra_user (is_active boolean not null, end_date timestamp(6), start_date timestamp(6), entra_user_id uuid not null, email varchar(255) not null unique, first_name varchar(255) not null, last_name varchar(255) not null, user_type varchar(255) check (user_type in ('USER','ADMIN')), primary key (entra_user_id))
create table entra_user_app_registration (entra_app_registration_id uuid not null, entra_user_id uuid not null, primary key (entra_app_registration_id, entra_user_id))
create table firm (firm_id uuid not null, …
```
=> STB-1570: Initial Version of Data Model for LAA

src/integrationTest/java/uk/gov/justice/laa/portal/landingpage/controller/UserControllerTest.java, src/main/java/uk/gov/justice/laa/portal/landingpage/controller/UserController.java, src/main/resources/templates/add-user-roles.html, src/main/resources/templates/manage-user.html, src/test/java/uk/gov/justice/laa/portal/landingpage/controller/UserControllerTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/UserServiceTest.java
- Added manage user - services tab/screen
- Added userAppRoles to manage-user model and injected userAppRoles variable to be used in the services tab
- Updated tests for manageUser user controller due to adding in userAppRoles 
- Added tests for getUserAppRolesByUserId as it's used to pull data from the graph API
https://github.com/user-attachments/assets/cce4cf4c-aaac-4a3d-9e51-253de791920e
=> Displays user app roles in user management views

build.gradle, src/integrationTest/java/uk/gov/justice/laa/portal/landingpage/repository/BaseRepositoryTest.java, src/integrationTest/java/uk/gov/justice/laa/portal/landingpage/repository/EntraAppRegistrationRepositoryTest.java, src/integrationTest/java/uk/gov/justice/laa/portal/landingpage/repository/EntraUserRepositoryTest.java, src/integrationTest/java/uk/gov/justice/laa/portal/landingpage/repository/FirmRepositoryTest.java, src/integrationTest/java/uk/gov/justice/laa/portal/landingpage/repository/LaaAppRepositoryTest.java, src/integrationTest/java/uk/gov/justice/laa/portal/landingpage/repository/LaaAppRoleRepositoryTest.java, src/integrationTest/java/uk/gov/justice/laa/portal/landingpage/repository/LaaUserProfileRepositoryTest.java, src/integrationTest/java/uk/gov/justice/laa/portal/landingpage/repository/OfficeRepositoryTest.java, src/integrationTest/resources/application-test.properties, src/integrationTest/resources/application.properties, src/main/java/uk/gov/justice/laa/portal/landingpage/entity/LaaApp.java, src/main/java/uk/gov/justice/laa/portal/landingpage/entity/LaaAppRole.java
Basic Repository tests were added. The PR introduced use of new test container libraries, so that a the tests are exercised against a Postgres docker container.
=> Baseline Repository tests added

src/main/resources/templates/manage-user.html
- Added hardcoded values for offices into manage user screen
https://github.com/user-attachments/assets/0d9ce962-4a94-41d0-b4b9-551a8d0d54c1
=> STB 1620 -  UI user details view offices 

src/integrationTest/java/uk/gov/justice/laa/portal/landingpage/repository/BaseRepositoryTest.java, src/integrationTest/java/uk/gov/justice/laa/portal/landingpage/repository/EntraUserRepositoryTest.java, src/main/java/uk/gov/justice/laa/portal/landingpage/entity/EntraUser.java, src/test/java/uk/gov/justice/laa/portal/landingpage/entity/BaseEntityTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/entity/EntraUserTest.java
STB-1570 - Added missing column user_name in  entra_user table
=> STB-1570 - Added missing column user_name in  entra_user table

build.gradle, src/main/resources/application.properties
STB-1330 - enable and expose application metrics for Prometheus via actuator endpoint.
=> Expose application metrics for Prometheus

src/main/java/uk/gov/justice/laa/portal/landingpage/repository/FirmRepository.java, src/main/java/uk/gov/justice/laa/portal/landingpage/utils/DemoDataPopulator.java
The data population causing duplicate entries error because there are multiple instances running. This is an attempt to stop re-insert data if already present.
https://dsdmoj.atlassian.net/browse/STB-1835
=> STB-1835: Stop repopulating the DB if dummy data already exists

.github/workflows/deploy_dev.yml, .github/workflows/deploy_test.yml
Actions step fails as suppressed error for not removing directories still returns a non-zero exit code, this change avoids this.
=> Avoid non-zero exit code as shell runs with -e

src/integrationTest/java/uk/gov/justice/laa/portal/landingpage/config/TestSecurityConfig.java, src/integrationTest/java/uk/gov/justice/laa/portal/landingpage/controller/AppSelectionTest.java, src/integrationTest/java/uk/gov/justice/laa/portal/landingpage/controller/UnauthenticatedTest.java, src/integrationTest/java/uk/gov/justice/laa/portal/landingpage/controller/UserControllerTest.java, src/main/java/uk/gov/justice/laa/portal/landingpage/config/MapperConfig.java, src/main/java/uk/gov/justice/laa/portal/landingpage/config/SecurityConfig.java, src/main/java/uk/gov/justice/laa/portal/landingpage/controller/UserController.java, src/main/java/uk/gov/justice/laa/portal/landingpage/dto/AppDto.java, src/main/java/uk/gov/justice/laa/portal/landingpage/dto/AppRoleDto.java, src/main/java/uk/gov/justice/laa/portal/landingpage/entity/App.java, src/main/java/uk/gov/justice/laa/portal/landingpage/service/UserService.java, src/main/resources/templates/edit-user-apps.html, src/main/resources/templates/edit-user-roles.html, src/test/java/uk/gov/justice/laa/portal/landingpage/controller/UserControllerTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/dto/AppDtoTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/dto/AppRoleDtoTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/UserServiceTest.java
1. Added new edit user app screen.
2. Added endpoints to handle screen and redirect to roles.
3. Changed roles to pull from DB rather than intra
4. Added unit tests.
5. Added integration tests.
6. Added integration test config to allow us to bypass auth when testing.
7. Omitted usual security config from tests.
8. Minor mapping bug fix for graph -> entra users.
New screen:
=> STB-1816: Edit user app assignment

src/main/java/uk/gov/justice/laa/portal/landingpage/controller/UserController.java, src/main/java/uk/gov/justice/laa/portal/landingpage/service/UserService.java, src/main/resources/templates/edit-user.html, src/main/resources/templates/manage-user.html, src/test/java/uk/gov/justice/laa/portal/landingpage/controller/UserControllerTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/UserServiceTest.java
Cleanup PR to ensure all endpoints are now pulling from the database when it comes to fetching users
=> Remove remaining synchronous Entra calls for fetching users by ID

src/main/java/uk/gov/justice/laa/portal/landingpage/utils/DemoDataPopulator.java
STB-1992 - Extra logging added for data population
=> STB-1992 - Extra logging added for data population

src/main/java/uk/gov/justice/laa/portal/landingpage/utils/DemoDataPopulator.java, src/test/java/uk/gov/justice/laa/portal/landingpage/utils/DemoDataPopulatorTest.java
STB-1685: Change the way the requested users are loaded
=> STB-1685: Change the way the requested users are loaded

src/main/java/uk/gov/justice/laa/portal/landingpage/controller/UserController.java, src/main/java/uk/gov/justice/laa/portal/landingpage/forms/UserDetailsForm.java, src/main/resources/templates/add-user-created.html, src/main/resources/templates/add-user-details.html, src/test/java/uk/gov/justice/laa/portal/landingpage/controller/UserControllerTest.java
https://github.com/user-attachments/assets/e43d8368-782d-4671-8420-190dacc43371
This pull request introduces several changes to the `UserController` and related files to improve functionality, enhance user experience, and address validation requirements. The key updates include refactoring session handling, enhancing form validation, updating templates for better user feedback, and modifying test cases to align with the changes.
* Refactored session attribute handling in `UserController` to improve readability and ensure proper cleanup of session data after user actions. [[1]](diffhunk://#diff-1c3931784714b5992966f392b56dad9140ea42ba7303dfce45c2cb8533ed3885L290-R310) [[2]](diffhunk://#diff-1c3931784714b5992966f392b56dad9140ea42ba7303dfce45c2cb8533ed3885L455-R467) …
=> Additional form validation + success page for newly created users

src/main/java/uk/gov/justice/laa/portal/landingpage/dto/ClaimEnrichmentResponse.java, src/main/java/uk/gov/justice/laa/portal/landingpage/service/ClaimEnrichmentService.java, src/test/java/uk/gov/justice/laa/portal/landingpage/controller/ClaimEnrichmentControllerTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/ClaimEnrichmentServiceTest.java
- Update Enrichment Response Object to reflect what Entra Expects for Claims
=> Updating Claim Enrichment Response DTO

src/main/java/uk/gov/justice/laa/portal/landingpage/service/ClaimEnrichmentService.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/ClaimEnrichmentServiceTest.java
- Updating naming convention for Entra Claims Mapping
- Updating success status in request, for more accurate logging
=> STB-1708: Update Entra Claim Names

src/main/java/uk/gov/justice/laa/portal/landingpage/entity/EntraUser.java
STB-2030 - Fix hibernate mapping for renamed field
=> STB-2030 - Fix hibernate mapping for renamed field

src/main/java/uk/gov/justice/laa/portal/landingpage/controller/LoginController.java, src/main/java/uk/gov/justice/laa/portal/landingpage/service/GraphApiService.java, src/main/java/uk/gov/justice/laa/portal/landingpage/service/LoginService.java, src/main/java/uk/gov/justice/laa/portal/landingpage/utils/RestUtils.java, src/main/resources/templates/index.html, src/main/resources/templates/partials/header.html, src/test/java/uk/gov/justice/laa/portal/landingpage/controller/LoginControllerTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/GraphApiServiceTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/LoginServiceTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/utils/RestUtilTest.java
Sign out
https://dsdmoj.atlassian.net/browse/STB-2129
=> STB-2129 logout

src/main/java/uk/gov/justice/laa/portal/landingpage/service/TechServicesClient.java
Removal of company name as it is causing tech services to fail the request.
=> STB-2118 - Revert removal of company name

src/main/java/uk/gov/justice/laa/portal/landingpage/service/TechServicesClient.java, src/main/java/uk/gov/justice/laa/portal/landingpage/techservices/RegisterUserRequest.java
STB-2118 - Removed the company name altogether
=> STB-2118 - Removed the company name altogether

src/integrationTest/java/uk/gov/justice/laa/portal/landingpage/repository/UserProfileRepositoryTest.java, src/main/java/uk/gov/justice/laa/portal/landingpage/entity/UserProfile.java, src/main/resources/db/changelog/db.changelog-master.yaml, src/test/java/uk/gov/justice/laa/portal/landingpage/entity/BaseEntityTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/entity/UserProfileTest.java
https://dsdmoj.atlassian.net/browse/STB-2219
=> STB-2219 Auto generate legacy user id

.github/workflows/deploy_dev.yml, .github/workflows/deploy_test.yml, deployments/templates/deployment.yml
Update env vars
https://dsdmoj.atlassian.net/browse/STB-1907
=> STB-1907 Internal user sync part 2

src/main/java/uk/gov/justice/laa/portal/landingpage/service/InternalUserPollingService.java
https://dsdmoj.atlassian.net/browse/STB-1907
=> STB-1907 Add pagination

src/main/java/uk/gov/justice/laa/portal/landingpage/service/InternalUserPollingService.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/InternalUserPollingServiceTest.java
https://dsdmoj.atlassian.net/browse/STB-1907
=> STB-1907 Add pagination - fix list

src/main/java/uk/gov/justice/laa/portal/landingpage/service/ClaimEnrichmentService.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/ClaimEnrichmentServiceTest.java
https://dsdmoj.atlassian.net/browse/STB-2343
- Return Legacy User ID in Claim Enrichment Response
- Return all firm office codes when external user has no default offices assigned
=> STB-2343: Return all firm office codes + LegacyUserID

src/main/java/uk/gov/justice/laa/portal/landingpage/config/SecurityConfig.java, src/test/java/uk/gov/justice/laa/portal/landingpage/config/SecurityConfigTest.java
https://dsdmoj.atlassian.net/browse/STB-2381
Update Logout Functionality to support GET method
=> STB-2381 logout support all methods

src/main/java/uk/gov/justice/laa/portal/landingpage/controller/UserController.java, src/main/java/uk/gov/justice/laa/portal/landingpage/service/UserService.java, src/main/resources/templates/add-user-offices.html, src/main/resources/templates/edit-user-offices.html, src/main/resources/templates/grant-access-check-answers.html, src/main/resources/templates/grant-access-user-offices.html, src/main/resources/templates/manage-user.html, src/main/resources/templates/user/offices.html, src/test/java/uk/gov/justice/laa/portal/landingpage/controller/UserControllerTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/UserServiceTest.java
=> Stb 2354 UI fixes

src/main/java/uk/gov/justice/laa/portal/landingpage/entity/FirmType.java
STB-2407 - Add more firm types
=> STB-2407 - Add more firm types

src/main/java/uk/gov/justice/laa/portal/landingpage/service/UserService.java
STB-2407  - Set status for polled internal users
=> STB-2407  - Set status for polled internal users

src/main/resources/data/laa-apps-details.yml
**To Be Reverted**
Temporarily disable PUI app on landing page to test STB-2312
=> Test STB-2312: Remove PUI

src/main/java/uk/gov/justice/laa/portal/landingpage/controller/LoginController.java, src/test/java/uk/gov/justice/laa/portal/landingpage/controller/LoginControllerTest.java
JIRA link: https://dsdmoj.atlassian.net/browse/STB-2450
Changed the isAdmin logic to use permissions rather than userType
=> STB-2450: Fixed bug where manage user link was always appearing regardless of admin permissions

src/main/java/uk/gov/justice/laa/portal/landingpage/controller/LoginController.java
user with view internal or external user permission should be able to view users
https://dsdmoj.atlassian.net/browse/STB-2454
=> STB-2454 bug fix, show view users link

src/main/java/uk/gov/justice/laa/portal/landingpage/controller/UserController.java, src/main/resources/templates/manage-user.html, src/test/java/uk/gov/justice/laa/portal/landingpage/controller/UserControllerTest.java
https://dsdmoj.atlassian.net/browse/STB-2413
Also show the updated wording on user details page
=> STB-2413 Offices on user details page

src/main/java/uk/gov/justice/laa/portal/landingpage/service/LiveTechServicesClient.java, src/main/java/uk/gov/justice/laa/portal/landingpage/service/UserService.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/UserServiceTest.java
STB-2471 - Revert call to tech services on role assignment
=> STB-2471 - Revert call to tech services on role assignment

src/main/java/uk/gov/justice/laa/portal/landingpage/service/LiveTechServicesClient.java
STB-2471 - Send only non-authz role apps to entra/ts
=> STB-2471 - Send only non-authz role apps to entra/ts

src/main/java/uk/gov/justice/laa/portal/landingpage/service/LiveTechServicesClient.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/LiveTechServicesClientTest.java
STB-2407 - change log to debug
=> STB-2407 - change log to debug

src/main/java/uk/gov/justice/laa/portal/landingpage/service/LiveTechServicesClient.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/LiveTechServicesClientTest.java
Reverts ministryofjustice/laa-landing-page#302
=> Revert "STB-2407 - change log to debug"

src/main/java/uk/gov/justice/laa/portal/landingpage/repository/EntraUserRepository.java, src/main/java/uk/gov/justice/laa/portal/landingpage/repository/UserProfileRepository.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/UserServiceTest.java
https://dsdmoj.atlassian.net/browse/STB-2506
- Fixed a bug where searching for a users full name was returning empty - e.g "Test User"
When searching for Test or User or test.user@example.com is working
=> STB-2506: Fix search functionality based on firstname + lastname

build.gradle
IDAM-3969 - Add missing dependency
=> IDAM-3969 - Add missing dependency

src/integrationTest/java/uk/gov/justice/laa/portal/landingpage/repository/AppRoleRepositoryTest.java, src/main/java/uk/gov/justice/laa/portal/landingpage/repository/AppRoleRepository.java, src/main/java/uk/gov/justice/laa/portal/landingpage/service/RoleAssignmentService.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/RoleAssignmentServiceTest.java
https://dsdmoj.atlassian.net/browse/STB-2512
=> STB-2512 fix non authz role display

src/integrationTest/java/uk/gov/justice/laa/portal/landingpage/repository/EntraUserRepositoryTest.java, src/main/java/uk/gov/justice/laa/portal/landingpage/repository/EntraUserRepository.java
fix Email validation does not block existing emails if entered in uppercase/lowercase
https://dsdmoj.atlassian.net/browse/STB-2511
=> STB-2511 Email validation

src/main/resources/db/changelog/changesets/db.changesets-2.7.yaml
https://dsdmoj.atlassian.net/browse/STB-2530
=> STB-2530 External User Manager can not manage external user admin

src/integrationTest/java/uk/gov/justice/laa/portal/landingpage/controller/RoleBaseAccessEditUserRoleTest.java, src/main/java/uk/gov/justice/laa/portal/landingpage/service/UserService.java
Removed the exception for authz roles in displayed roles
=> Fixed bug where authz roles where appearing in the edit user screen which could not be assigned.

src/integrationTest/java/uk/gov/justice/laa/portal/landingpage/controller/RoleBasedAccessIntegrationTest.java, src/integrationTest/java/uk/gov/justice/laa/portal/landingpage/controller/RoleBasedAccessOfficeTest.java, src/main/java/uk/gov/justice/laa/portal/landingpage/service/UserService.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/UserServiceTest.java
- Added validation to check office firm vs user firm.
- Added integration tests.
- Updated unit tests.
JIRA link: https://dsdmoj.atlassian.net/browse/STB-2575
=> STB -2575: Fixed bug where users could be assigned offices outside of their firm.

src/main/java/uk/gov/justice/laa/portal/landingpage/forms/FirmSearchForm.java, src/test/java/uk/gov/justice/laa/portal/landingpage/forms/FirmSearchFormTest.java
https://dsdmoj.atlassian.net/browse/STB-2563
=> STB-2563 firm search validation message should only display once

src/main/java/uk/gov/justice/laa/portal/landingpage/controller/UserController.java, src/main/java/uk/gov/justice/laa/portal/landingpage/entity/UserType.java, src/main/java/uk/gov/justice/laa/portal/landingpage/service/AccessControlService.java, src/main/java/uk/gov/justice/laa/portal/landingpage/utils/DemoDataPopulator.java, src/test/java/uk/gov/justice/laa/portal/landingpage/controller/UserControllerTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/entity/UserTypeTest.java
JIRA Link: https://dsdmoj.atlassian.net/browse/STB-2586
- Removed GLOBAL_ADMIN from user types and replaced references with hard-coded string.
- Added validation to the post request send to create user to make sure user type provided is external.
- Updated tests and added new test case
=> STB-2586: Fixed bug where internal user types could be injected into the create external user flow

src/integrationTest/java/uk/gov/justice/laa/portal/landingpage/controller/RoleBasedAccessGrantAccessTest.java, src/main/java/uk/gov/justice/laa/portal/landingpage/controller/UserController.java
- Added PreAuthorize annotation to the grant-access endpoints
- Added integration tests
=> Added user authorization to the grant user access flow

src/main/java/uk/gov/justice/laa/portal/landingpage/controller/UserController.java, src/test/java/uk/gov/justice/laa/portal/landingpage/controller/UserControllerTest.java
STB-2596 - Potential bug fix for ccms role assignment
=> STB-2596 - Potential bug fix for ccms role assignment

src/main/java/uk/gov/justice/laa/portal/landingpage/entity/UserType.java, src/main/java/uk/gov/justice/laa/portal/landingpage/service/UserService.java
- Removed logic to assign authz roles on user creation
=> Fixed bug where external user admin was being assigned "External User Admin" role on creation when Provider Admin user type is selected.

src/main/java/uk/gov/justice/laa/portal/landingpage/service/GraphApiService.java, src/main/java/uk/gov/justice/laa/portal/landingpage/service/LoginService.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/GraphApiServiceTest.java
Stb 2503 - Further debugging logout issue on dev (to be reverted)
=> Stb 2503 - Further debugging logout issue on dev (to be reverted)

src/main/resources/templates/grant-access-check-answers.html
https://dsdmoj.atlassian.net/browse/STB-2601
=> STB-2601 Remove "remove" button

src/main/java/uk/gov/justice/laa/portal/landingpage/service/GraphApiService.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/GraphApiServiceTest.java
Reverts ministryofjustice/laa-landing-page#350
=> Revert "Stb 2503 - Further debugging logout issue on dev (to be reverted)"

src/main/java/uk/gov/justice/laa/portal/landingpage/controller/LoginController.java, src/main/java/uk/gov/justice/laa/portal/landingpage/service/CustomLogoutHandler.java, src/test/java/uk/gov/justice/laa/portal/landingpage/controller/LoginControllerTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/CustomLogoutHandlerTest.java
Reverts ministryofjustice/laa-landing-page#354
=> Revert "Always force Azure logout"

src/integrationTest/java/uk/gov/justice/laa/portal/landingpage/controller/RoleBasedAccessUserListTest.java, src/main/java/uk/gov/justice/laa/portal/landingpage/controller/UserController.java, src/main/java/uk/gov/justice/laa/portal/landingpage/repository/UserProfileRepository.java, src/main/java/uk/gov/justice/laa/portal/landingpage/service/UserService.java, src/test/java/uk/gov/justice/laa/portal/landingpage/controller/UserControllerTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/UserServiceTest.java
- Removed user type logic for firm admins
- Simplified controller logic for user list.
- Added logic to query to get external user managers when firm admins flag is set.
- Updated tests.
=> STB-2606: Reconciled user list conflicts

src/integrationTest/java/uk/gov/justice/laa/portal/landingpage/controller/AppSelectionTest.java, src/main/java/uk/gov/justice/laa/portal/landingpage/controller/AuthorisationController.java, src/main/java/uk/gov/justice/laa/portal/landingpage/controller/UserController.java, src/main/resources/templates/not-authorised.html, src/test/java/uk/gov/justice/laa/portal/landingpage/controller/AuthorisationControllerTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/controller/UserControllerTest.java
Added "Not authorised" page for handling users without permission to manage/view user details
https://github.com/user-attachments/assets/a789575d-93c8-47c7-ab3b-ac8ee1d526a3
**Authorization error handling improvements:**
* Added a new `AuthorisationController` with a `/not-authorised` endpoint to display a user-friendly "Not Authorised" page when access is denied (`AuthorisationController.java`, `not-authorised.html`). [[1]](diffhunk://#diff-d26c809df45cd3677fcf94449c6bddecf8908f59773ddd4a5ae42a96af4bc50dR1-R23) [[2]](diffhunk://#diff-8645ba00a74632c80b7206f16513a12c889fd7061c603f489264a825ef8b6c9fR1-R36)
* Updated `UserController` to catch `AuthorizationDeniedException` and `AccessDeniedException`, redirecting users to `/not-authorised` and logging a warning when authorization fails …
=> Add not authorised page

build.gradle
Reverts ministryofjustice/laa-landing-page#377
=> Revert "Readd Sentry springboot plugin"

src/main/java/uk/gov/justice/laa/portal/landingpage/repository/UserProfileRepository.java
STB-2642 - Added missing fetch
=> STB-2642 - Added missing fetch

src/main/java/uk/gov/justice/laa/portal/landingpage/service/ClaimEnrichmentService.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/ClaimEnrichmentServiceTest.java
Return legacyUserId.toUpperCase through claim enrichment service
=> STB-2680: Claim Enrichment Username to Upper

src/main/resources/templates/manage-user.html, src/main/resources/templates/users.html
https://dsdmoj.atlassian.net/browse/STB-2687
=> STB-2687 Change "pending" status text to "incomplete"

src/main/resources/application.properties
Reverts ministryofjustice/laa-landing-page#407
=> Revert "use client id only for audienc"

src/main/java/uk/gov/justice/laa/portal/landingpage/controller/UserController.java, src/main/java/uk/gov/justice/laa/portal/landingpage/dto/UserSearchCriteria.java, src/main/java/uk/gov/justice/laa/portal/landingpage/forms/FirmSearchForm.java, src/main/java/uk/gov/justice/laa/portal/landingpage/repository/UserProfileRepository.java, src/main/java/uk/gov/justice/laa/portal/landingpage/service/FirmService.java, src/main/java/uk/gov/justice/laa/portal/landingpage/service/UserService.java, src/main/java/uk/gov/justice/laa/portal/landingpage/utils/DemoDataPopulator.java, src/main/resources/templates/manage-user.html, src/main/resources/templates/users.html, src/test/java/uk/gov/justice/laa/portal/landingpage/controller/PdaControllerTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/controller/UserControllerTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/dto/UserSearchCriteriaTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/forms/FirmSearchFormTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/FirmServiceTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/UserServiceTest.java
- Added firm search top users listing (searches over firm name and code)
- Searches alongside existing  user name/email search functionality and compounds search
https://github.com/user-attachments/assets/2f3e54ed-ca25-484c-993b-a5077806ca3b
**User and Firm Search Enhancements:**
* Added a new `UserSearchCriteria` DTO to encapsulate user search parameters, and refactored the user search flow in `UserController` and `UserService` to use this object, allowing for more flexible and maintainable search logic. [[1]](diffhunk://#diff-1c3931784714b5992966f392b56dad9140ea42ba7303dfce45c2cb8533ed3885R113-R155) [[2]](diffhunk://#diff-97d1320488dab8c1c4e80b5c42d35bc33533849aa1c06435263412e7f3aedf8aR1-R67)
* Implemented a new `/user/firms/search` endpoint in `UserController` to allow searching for …
=> STB-2478: User search filter by Firm

src/main/java/uk/gov/justice/laa/portal/landingpage/exception/GlobalExceptionHandler.java, src/test/java/uk/gov/justice/laa/portal/landingpage/exception/GlobalExceptionHandlerTest.java
https://dsdmoj.atlassian.net/browse/STB-2681
fix APIs return 302 instead of 401 for unauthorised access
=> STB-2681 handle 401 Unauthorised error

src/main/resources/templates/users.html
STB-2746 - Fix show firm admin checkbox behaviour
https://dsdmoj.atlassian.net/browse/STB-2746
Fixed behaviour:
https://github.com/user-attachments/assets/15e4a70b-e43a-4880-8a1b-9e9aa39bb99b
=> STB-2746 - Fix show firm admin checkbox behaviour

src/main/resources/data/laa-apps-details.yml
https://dsdmoj.atlassian.net/browse/STB-2765
=> STB-2765 Change account linking service description

src/main/resources/templates/manage-user.html
Small text update - LSC account number -> Account number
=> LSC account number -> Account number

src/integrationTest/java/uk/gov/justice/laa/portal/landingpage/controller/LogoutIntegrationTest.java, src/main/java/uk/gov/justice/laa/portal/landingpage/controller/LoginController.java, src/main/java/uk/gov/justice/laa/portal/landingpage/service/CustomLogoutHandler.java, src/main/java/uk/gov/justice/laa/portal/landingpage/service/LoginService.java, src/main/java/uk/gov/justice/laa/portal/landingpage/service/LogoutService.java, src/test/java/uk/gov/justice/laa/portal/landingpage/controller/LoginControllerTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/CustomLogoutHandlerTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/LoginServiceTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/LogoutServiceTest.java
Refactor login and logout handling to redirect to Azure
https://github.com/user-attachments/assets/5c79932a-426e-42a4-86ac-a01be091d4a5
**Authentication Flow Improvements:**
* The login flow now always redirects to the Azure login URL, even if the email is blank or null, removing the previous error flash message and fallback to the local login page. A new `buildAzureLoginUrl()` method (without email) was added to `LoginService` for this purpose. (`LoginController.java`, `LoginService.java`, `LoginControllerTest.java`) [[1]](diffhunk://#diff-e58b1e8d630792f010684c11caaf85b16d7467a0d19818409119dc7fdfb8d9dbL57-L67) [[2]](diffhunk://#diff-798f2267281d6d306a6d845efd8908d1013524c93643655fc850685bbb21dc03L68-R89) [[3]](diffhunk://#diff-3a5cbec1aa999a1d7e2954dc7a136c381bbcec8588975397c5d1ec4a4a0f4 …
=> STB-2759 - Refactor login and logout handling to redirect to Azure

src/integrationTest/java/uk/gov/justice/laa/portal/landingpage/controller/LogoutIntegrationTest.java, src/main/java/uk/gov/justice/laa/portal/landingpage/controller/LoginController.java, src/main/java/uk/gov/justice/laa/portal/landingpage/service/CustomLogoutHandler.java, src/main/java/uk/gov/justice/laa/portal/landingpage/service/LoginService.java, src/main/java/uk/gov/justice/laa/portal/landingpage/service/LogoutService.java, src/test/java/uk/gov/justice/laa/portal/landingpage/controller/LoginControllerTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/CustomLogoutHandlerTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/LoginServiceTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/LogoutServiceTest.java
Reverts ministryofjustice/laa-landing-page#448
Reverting until later confirmation for go/no go from @callumbrettmoj
=> STB-2759 - Revert "STB-2759 - Refactor login and logout handling to redirect to Azure"

.github/pull_request_template.md, .github/workflows/check_env_vars.yml, src/main/resources/application.properties
Adding a check that any environment variables added to the code are properly configured to in the deployment files
---
- A new workflow that checks all new added environment variables are present in deployment files
- The workflow will comment on any PR with the missing configurations
---
---
---
=> STB-2782: Add configuration check for environment variables used in live environments

.idea/misc.xml, src/main/java/uk/gov/justice/laa/portal/landingpage/config/TechServicesConfig.java, src/main/java/uk/gov/justice/laa/portal/landingpage/controller/UserController.java, src/main/java/uk/gov/justice/laa/portal/landingpage/exception/TechServicesClientException.java, src/main/java/uk/gov/justice/laa/portal/landingpage/service/DoNothingTechServicesClient.java, src/main/java/uk/gov/justice/laa/portal/landingpage/service/LiveTechServicesClient.java, src/main/java/uk/gov/justice/laa/portal/landingpage/service/TechServicesClient.java, src/main/java/uk/gov/justice/laa/portal/landingpage/service/UserService.java, src/main/java/uk/gov/justice/laa/portal/landingpage/techservices/TechServicesApiResponse.java, src/main/java/uk/gov/justice/laa/portal/landingpage/techservices/TechServicesErrorResponse.java, src/main/resources/templates/add-user-check-answers.html, src/test/java/uk/gov/justice/laa/portal/landingpage/config/TechServicesConfigTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/controller/UserControllerTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/DoNothingTestServiceClientTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/LiveTechServicesClientTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/UserServiceTest.java
https://dsdmoj.atlassian.net/browse/STB-2857
https://github.com/user-attachments/assets/fac55582-13a0-4495-b878-1037687917e9
---
- 
- 
- 
---
---
---
=> STB-2857: Handle 409 (user conflict error) from TS and log the 409 as debug

src/main/java/uk/gov/justice/laa/portal/landingpage/service/EmailValidationService.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/EmailValidationServiceTest.java
https://dsdmoj.atlassian.net/browse/STB-2858
---
- 
- 
- 
---
---
---
=> STB-2858 - Speed up EmailValidationServiceTest run

deployments/templates/deployment.yml
STB-2723 - Add missing double quote in deployment.yml
---
- 
- 
- 
---
---
---
=> STB-2723 - Add missing double quote in deployment.yml

src/main/resources/db/changelog/changesets/db.changesets-3.5.yaml
1. STB-2900: Add sorting order for app and app role display
2. Remove Role assignment permission for Firm User Manager
3. The app sorting order has been specified in STB-2700.
https://dsdmoj.atlassian.net/browse/STB-2900
---
- 
- 
- 
---
---
---
=> STB-2900: Add sorting order for app and app role display

.github/workflows/check_env_vars.yml
=> STB-2782: Fix environment variable CICD check

src/main/java/uk/gov/justice/laa/portal/landingpage/config/SecurityConfig.java
---
https://dsdmoj.atlassian.net/browse/STB-2958
- https://github.com/spring-projects/spring-session/issues/2564
- 
- 
---
---
---
=> STB-2958 update session on duplicated index

src/main/java/uk/gov/justice/laa/portal/landingpage/controller/UserController.java, src/test/java/uk/gov/justice/laa/portal/landingpage/controller/UserControllerTest.java
usually the size of selected apps should match the max selectedAppIndex unless data broke. added error handling for this
---
- 
- 
- 
---
---
---
=> STB-2959 Unknown app in check your answer page

src/main/java/uk/gov/justice/laa/portal/landingpage/model/LaaApplication.java, src/main/java/uk/gov/justice/laa/portal/landingpage/model/LaaApplicationForView.java, src/main/java/uk/gov/justice/laa/portal/landingpage/model/UserSessionData.java, src/main/java/uk/gov/justice/laa/portal/landingpage/service/LoginService.java, src/main/java/uk/gov/justice/laa/portal/landingpage/service/UserService.java, src/main/resources/data/laa-apps-details.yml, src/test/java/uk/gov/justice/laa/portal/landingpage/controller/LoginControllerTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/model/LaaApplicationForViewTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/LoginServiceTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/UserServiceTest.java
https://dsdmoj.atlassian.net/browse/STB-2758
Conditional display of app description on landing page
---
- 
- 
- 
---
---
---
=> STB-2758 - Conditional display of app description on the landing page

src/main/resources/templates/add-user-check-answers.html
Display Firm ID on “Check Your Answers” Screen During User Creation
https://dsdmoj.atlassian.net/browse/STB-2946
---
- 
- 
- 
---
---
---
=> STB-2946 check your answer display firm code

Dockerfile
=> STB-2782: Update openssl

.github/workflows/trivy_docker.yaml, Dockerfile-WorkFlow
=> STB-2782: Fix Trivy
