ministryofjustice/laa-landing-page

src/main/java/uk/gov/justice/laa/portal/landingpage/config/GraphClientConfig.java, src/main/java/uk/gov/justice/laa/portal/landingpage/config/TokenAuthAccessProvider.java, src/main/java/uk/gov/justice/laa/portal/landingpage/controller/LoginController.java, src/main/java/uk/gov/justice/laa/portal/landingpage/model/LaaApplication.java, src/main/java/uk/gov/justice/laa/portal/landingpage/model/UserSessionData.java, src/main/java/uk/gov/justice/laa/portal/landingpage/service/GraphApiService.java, src/main/java/uk/gov/justice/laa/portal/landingpage/service/LaaAppDetailsStore.java, src/main/java/uk/gov/justice/laa/portal/landingpage/service/LoginService.java, src/main/java/uk/gov/justice/laa/portal/landingpage/utils/RestUtils.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/GraphApiServiceTest.java
This PR will provide the ability to load the user applications and the corresponding user specific roles and render them on landing page. As not many of us configured for user role access, it may not show many apps on the landing page when run locally. So the application list is stored in user session for now and not implemented the rendering. It can be easily done near future once we get the apps setup with user roles for most of us.
=> STB-1452-Implement-dynamic-apps-using-app-roles

build.gradle
Removed redundant dependency declaration. The dependant library version numbers are now pulled from common location.
=> STB-1536 - Removed redundant dependency declaration

.github/workflows/zap_dast_daily_dev.yml, .github/workflows/zap_dast_weekly_test.yml
ZAP Scan support has been added. Two git workflows added to run a daily baseline scan and a weekly full scan. A report will be generated if there are any issues and corresponding Github issue gets created. A slack notification is sent to notify the channel subscribers.
All these changes are created from zap-dast-test branch. Below is the screenshot of Slack notificaiton
=> STB-1306 - ZAP Scan support for laa-landing-page

deployments/templates/servicemonitor.yml
Fix to instruct Prometheus to access the actuator endpoint on the correct port, to be able to collect metrics.
https://dsdmoj.atlassian.net/browse/STB-1320
=> Fix port for prometheus actuator service monitor (STB-1320)

database/Dockerfile
Running containers with 'root' user can lead to a container escape situation. (High level vuln raised by Snyk)
=> Fix: adding USER to Dockerfile to prevent root access vuln

deployments/templates/deployment.yml
Snyk Vulnerability message: Container 'laa-landing-page' of Deployment 'laa-landing-page' should set 'securityContext.readOnlyRootFilesystem' to true
=> Fix: make root filesystem immutable

.github/workflows/deploy_dev.yml, .github/workflows/deploy_test.yml, deployments/templates/grafanadashboard.yml, deployments/templates/prometheus.yml
- Adds custom alerts for our RDS databases
- Adds panels to display RDS metrics in our Grafana dashboards
- Reordered deployment to deploy monitoring in a separate step after deployment of other Cloud Platform resources, to ensure can gain database identifier after it exists
- Small improvements to Grafana dashboard json model to make it easier to edit in future, e.g. using templating variables
- Small improvements to current alerts
https://dsdmoj.atlassian.net/browse/STB-1714
=> Add RDS alerts and metrics, and refine existing monitoring (STB-1714)

src/main/java/uk/gov/justice/laa/portal/landingpage/config/SecurityConfig.java, src/test/java/uk/gov/justice/laa/portal/landingpage/config/SecurityConfigTest.java
STB-1724
- Configure /enrich endpoints to be excluded from CSRF Invalid Token errors
- Updated associated tests (Spring default is a redirect to Login)
The /enrich endpoint is already protected with @PreAuthorize("isAuthenticated()")
All requests go through OAuth2 authentication with Entra
Unauthenticated requests are redirected to Azure login
=> STB-1724: Disable CSRF on /enrich endpoint

src/main/resources/templates/users.html
This pull request simplifies the user management interface by removing the ability to select and disable multiple users at once. The changes focus on improving the clarity and usability of the `users.html` template.
* Removed the checkbox column from the user table, which allowed administrators to select users for disabling. (`src/main/resources/templates/users.html`, [[1]](diffhunk://#diff-5706460a5d76531ccf89d49fc69ba9783f296fd514786f7fa47ba80966473bd1L91-L93) [[2]](diffhunk://#diff-5706460a5d76531ccf89d49fc69ba9783f296fd514786f7fa47ba80966473bd1L107-L116)
* Removed the "Disable selected" button, which was used to disable the selected users. (`src/main/resources/templates/users.html`, [src/main/resources/templates/users.htmlL130](diffhunk://#diff-5706460a5d76531ccf89d49fc69ba9783f296fd51 …
=> Remove user selection checkboxes and disable button from users table

src/main/java/uk/gov/justice/laa/portal/landingpage/forms/UserDetailsForm.java, src/main/resources/templates/add-user-details.html
**Email field - size (max 254 characters) + format validation. 
Names fields - size (max 99 characters) validation**
This pull request introduces validation improvements for user input fields and enhances error message rendering in the user details form. The key changes include adding character length constraints to form fields and updating the HTML templates to use semantic tags for error messages.
* [`src/main/java/uk/gov/justice/laa/portal/landingpage/forms/UserDetailsForm.java`](diffhunk://#diff-dcce0d0ac1ee4fc81c3f944d9d79b993905f5ce038b62ccbc6a689367442dbf2R6-R22): Added `@Size` constraints to the `firstName`, `lastName`, and `email` fields to enforce maximum character limits (99 for names, 254 for email). Updated the `@Email` annotation to include a custom error message.
* …
=> Email field - size/format validation. Names fields - size validation

src/main/resources/templates/users.html
https://github.com/user-attachments/assets/c218e87e-5736-42ac-a901-b773877eb830
This pull request updates the `users.html` template to enhance accessibility, improve styling consistency with the GOV.UK Design System, and add new functionality for filtering user data. The most important changes include modifying button text, updating label and hint styling, adding a new filter for firm admins, and refining table row classes.
* Updated button text from "Create a user" to "Create a new user" for improved clarity. (`src/main/resources/templates/users.html`, [src/main/resources/templates/users.htmlL56-R56](diffhunk://#diff-5706460a5d76531ccf89d49fc69ba9783f296fd514786f7fa47ba80966473bd1L56-R56))
* Adjusted label and hint styling by adding `govuk-label--m` and `govuk-!-margin-top-1` classes for …
=> Add show firm admins checkbox to user listing screen

src/integrationTest/java/uk/gov/justice/laa/portal/landingpage/controller/UserCreationTest.java, src/main/java/uk/gov/justice/laa/portal/landingpage/controller/UserController.java, src/main/java/uk/gov/justice/laa/portal/landingpage/exception/CreateUserDetailsIncompleteException.java, src/main/java/uk/gov/justice/laa/portal/landingpage/exception/GlobalExceptionHandler.java, src/test/java/uk/gov/justice/laa/portal/landingpage/controller/UserControllerTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/exception/CreateUserDetailsIncompleteExceptionTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/exception/GlobalExceptionHandlerTest.java
A user was previously able to skip stages of user creation if they went directly to the relevant URL instead of going through the whole flow. This usually ended in the server throwing a 500 error. Added error handling to stop this.
- Added new exception CreateUserDetailsIncompleteException
- Added global exception handling for new exception
- Added logic to throw new exception when the user goes directly to screen they shouldnt access yet.
- Updated old unit tests.
- Added new unit tests.
- Added integration tests.
JIRA link: https://dsdmoj.atlassian.net/browse/STB-2085
=> STB-2085: Added error handling to redirect user back to create user details screen if they skip ahead.

src/main/java/uk/gov/justice/laa/portal/landingpage/controller/UserController.java, src/main/java/uk/gov/justice/laa/portal/landingpage/service/UserService.java, src/test/java/uk/gov/justice/laa/portal/landingpage/controller/UserControllerTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/UserServiceTest.java
https://dsdmoj.atlassian.net/browse/STB-2259
Create user offices were not being persisted to database. Fix added includes the following:
This pull request introduces changes to improve how offices are retrieved based on firms, updates related test cases, and simplifies the repository queries. The most important changes include replacing the `getOffices` method with `getOfficesByFirms`, ensuring firm data is passed in session attributes, and modifying repository calls to use `findAllById` instead of `findOfficeByFirm_IdIn`.
* [`src/main/java/uk/gov/justice/laa/portal/landingpage/controller/UserController.java`](diffhunk://#diff-1c3931784714b5992966f392b56dad9140ea42ba7303dfce45c2cb8533ed3885L359-R361): Updated methods `offices` and `postOffices` to use `officeService.getOfficesByFirms` …
=> STB-2259 - Bug: Create user - Office selection not persisted to  database

src/main/java/uk/gov/justice/laa/portal/landingpage/service/ClaimEnrichmentService.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/ClaimEnrichmentServiceTest.java
- Return office code in claim enrichment response
- Some apps like Crime Apply requires the office code to be passed in a claim
=> STB-1735: Return office code in Claim Enrichment

src/main/resources/templates/grant-access-confirmation.html
This pull request updates the `grant-access-confirmation.html` template to improve clarity and consistency in user-facing messages. The changes focus on refining headings, instructions, and button text for better user experience.
* Updated the confirmation panel title from "Access updated" to "Access and permissions updated" for greater specificity.
* Changed the subheading "What happens next" to "Next steps" for conciseness.
* Replaced the bullet-point instructions with a single paragraph instructing administrators to contact the user about their updated access and permissions.
* Modified the button text to use sentence case for consistency: "Go back to Manage your users" changed to "Go back to manage your users."
=> Update grant access confirmation message and next steps content

src/main/resources/templates/add-user-created.html
Intended as a temporary fix. No External users will actually have emails sent at this stage, so the message is misleading.
=> Fix: remove email verification message in success page

src/integrationTest/java/uk/gov/justice/laa/portal/landingpage/controller/RoleBasedAccessIntegrationTest.java, src/integrationTest/java/uk/gov/justice/laa/portal/landingpage/controller/RoleBasedAccessUserListTest.java, src/main/java/uk/gov/justice/laa/portal/landingpage/controller/UserController.java
Moved logic of `showFirmAdmins` from permission logic to filtering list according to userTypes
https://github.com/user-attachments/assets/54807a94-771c-4c66-a4f1-c9d92554c8ed
User type filtering improvements:
* Introduced a new `userTypesToFilter` variable to explicitly control which user types are included in the results, making the filtering logic clearer and easier to maintain.
* When `showFirmAdmins` is true, the results are now filtered to only include `EXTERNAL_SINGLE_FIRM_ADMIN` users; otherwise, all external user types are included by default.
* For users with permission to see all users, the method now combines the filtered external user types with the `INTERNAL` user type, ensuring the correct set of users is returned based on permissions and filter flags.
* Updated all calls to …
=> Fixed showFirmAdmins filter on user listing

src/main/java/uk/gov/justice/laa/portal/landingpage/controller/LoginController.java, src/main/resources/templates/edit-user-apps.html, src/main/resources/templates/edit-user-details.html, src/main/resources/templates/edit-user-offices.html, src/main/resources/templates/edit-user-roles.html, src/main/resources/templates/error.html, src/main/resources/templates/grant-access-check-answers.html, src/main/resources/templates/grant-access-confirmation.html, src/main/resources/templates/grant-access-user-apps.html, src/main/resources/templates/grant-access-user-offices.html, src/main/resources/templates/grant-access-user-roles.html, src/main/resources/templates/home.html, src/main/resources/templates/manage-user.html, src/main/resources/templates/not-authorised.html, src/main/resources/templates/partials/header.html, src/main/resources/templates/users.html, src/test/java/uk/gov/justice/laa/portal/landingpage/controller/LoginControllerTest.java
- Updated breadcrumb navigation across various templates to improve user experience.
- Changed pageCategory from 'register' to 'grant-access' in grant access related templates.
- Simplified breadcrumb structure by removing unnecessary list elements.
- Adjusted header links to point to the correct home page.
- Enhanced error and not-authorised pages with consistent navigation.
- Modified home page link to remove target="_blank" for better usability.
- Updated manage user template to reflect correct page title and navigation.
- Improved pagination structure and styling in users template for better clarity.
- Refactored LoginControllerTest to ensure proper redirection and model attribute handling.
**Navigation and Breadcrumb Improvements:**
* Replaced breadcrumb lists with consistent "Back" …
=> Refactor user access management templates and navigation

build.gradle
The following log message was seen when testing the prod JWT decoder:
`Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts`
We've been seeing logs being disabled in our test environments, exploring the removal of this jar from the classpath as a potential fix.
=> Excluded commons-logging from classpath to avoid logger conflicts.

src/main/java/uk/gov/justice/laa/portal/landingpage/controller/LoginController.java, src/main/resources/templates/home.html, src/test/java/uk/gov/justice/laa/portal/landingpage/controller/LoginControllerTest.java
Add user role checks and custom messages for users without roles
**EXTERNAL**
**INTERNAL**
User experience improvements:
* The `home` method in `LoginController.java` now checks if a user has no roles assigned and determines if the user is internal or external, setting new model attributes `userHasNoRoles` and `isInternalUser` accordingly. This enables conditional display of custom messages.
* The `home.html` template displays a custom inset message when a user has no roles, instructing internal users to contact the MOJ Service Desk and external users to contact their Firm Admin. If the user has roles, the usual application list is shown. [[1]](diffhunk://#diff-52f0dda0be57fa81112f251bcbc39bf2da14185ed79da901061cc07d17742b6aR35-R44) …
=> Add user role checks and custom messages for users without roles

src/main/resources/templates/grant-access-check-answers.html, src/main/resources/templates/grant-access-user-apps.html, src/main/resources/templates/grant-access-user-roles.html, src/main/resources/templates/manage-user.html
Update page titles and categories from 'Grant Access' to 'Manage Access'
**UI terminology updates:**
* Updated the page title and `pageCategory` variable from "Grant Access" to "Manage Access" in the following templates: `grant-access-check-answers.html`, `grant-access-user-apps.html`, and `grant-access-user-roles.html`. [[1]](diffhunk://#diff-e754d3f165de717dfc3bbb8d91223484668b5722d1a0050d76033eac52755009L5-R9) [[2]](diffhunk://#diff-8760a4fea45f6365de3c0e9c9cfdbdf16512cf1f8a9e6bd6bfbbefa9f070b050L5-R9) [[3]](diffhunk://#diff-49e6e20271b574307572d8c7c84188ead2e7222e89125c8a44505d1085e0cc11L5-R9)
* Changed the button label from "Grant access" to "Manage access" in the `manage-user.html` template.
=> STB-2478 - Update page titles and categories from 'Grant Access' to 'Manage Access'

src/main/resources/templates/users.html
**Template structure and markup:**
* Moved the closing tags for `fieldset`, `.govuk-!-margin-top-4`, and associated `div`s to ensure proper nesting and semantic structure of the form and its controls. This improves maintainability and accessibility. [[1]](diffhunk://#diff-5706460a5d76531ccf89d49fc69ba9783f296fd514786f7fa47ba80966473bd1L131-R135) [[2]](diffhunk://#diff-5706460a5d76531ccf89d49fc69ba9783f296fd514786f7fa47ba80966473bd1R164-R166)
* Reformatted the `selectedFirmId` hidden input for better readability, splitting it across multiple lines.
**Visual and layout adjustments:**
* Updated the `.search-card` styling by removing the background color and adding a bottom border for a cleaner visual separation.
**Table column sizing:**
* Adjusted the width of the "Email" column from 35% to …
=> Refactor users.html: Clean up search form card and adjust styling for user listing (prevent horizontal scroll on full screen)

src/main/resources/templates/users.html
EXTERNAL was not accounted for a user type in our UI, adding it as an option.
=> Added EXTERNAL as an option in the user list table

src/main/java/uk/gov/justice/laa/portal/landingpage/service/UserService.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/UserServiceTest.java
when removing own role is unclear and exposes UUID
=> STB-2777 Error message

src/main/resources/templates/manage-user.html
- Add LSC account number along with office tab formatting
- Added min height for all panels
- Added "Go back to mange your users" button at bottom of panels
https://github.com/user-attachments/assets/48ba912e-d012-43ba-b649-5e750d9162a4
**User interface improvements:**
* Replaced the office summary list with a table that displays office addresses and LSC account numbers for better readability and structure. Also updated the messaging for users with no assigned offices or with access to all offices.
* Added a "Go back to manage your users" button at the bottom of the page for easier navigation.
* Changed the action link text from "Edit" to "Change" for both the apps and offices sections to align with GOV.UK design patterns. [[1]](diffhunk://#diff-e687d7fb36c1e4429780d9d4c1569e1332afd69837e8 …
=> Office formatting with LSC account number

.github/workflows/check_env_vars.yml, build.gradle, src/main/resources/logback-spring.xml
Currently it is very hard to look at logs in OpenSearch due to stack traces being printed line by line - this change makes it so things are printed as a one line JSON instead when on a live environment.
I am unsure how OpenSearch will react so need to deploy this to test it.
---
- Logs are now printed as JSON in live environments
---
---
---
=> STB-2791: Test single line logging on live environments

build.gradle, src/main/resources/application.properties
Add OpenTelemetry to Sentry to allow DB exports
---
- Add OpenTelemetry to Sentry to allow DB exports
---
---
---
=> STB-2782: Add OpenTelemetry to Sentry for DB exports

src/main/resources/templates/partials/footer.html
https://github.com/user-attachments/assets/fc48caea-5fb2-4013-b3fa-d3707b6e3d66
This pull request updates the support links in the footer to point directly to the official PDF documents for the privacy policy and terms and conditions, improving clarity and user experience.
Support links update:
* Changed the `Privacy policy` link in `footer.html` to reference the official user privacy notice PDF instead of a general help and information page.
* Changed the `Terms and conditions` link in `footer.html` to reference the official terms and conditions PDF instead of a general help and information page.
---
---
=> STB-2938 - Update footer links to point to the latest privacy policy and terms and terms links

src/integrationTest/java/uk/gov/justice/laa/portal/landingpage/controller/RoleBaseAccessEditUserRoleTest.java, src/integrationTest/java/uk/gov/justice/laa/portal/landingpage/controller/RoleBasedAccessIntegrationTest.java, src/integrationTest/java/uk/gov/justice/laa/portal/landingpage/controller/RoleBasedAccessUserListTest.java, src/integrationTest/java/uk/gov/justice/laa/portal/landingpage/repository/RoleCoverageIntegrationTest.java, src/main/java/uk/gov/justice/laa/portal/landingpage/controller/UserController.java, src/main/java/uk/gov/justice/laa/portal/landingpage/repository/RoleAssignmentRepository.java, src/main/java/uk/gov/justice/laa/portal/landingpage/service/RoleAssignmentService.java, src/test/java/uk/gov/justice/laa/portal/landingpage/controller/UserControllerTest.java, src/test/java/uk/gov/justice/laa/portal/landingpage/service/RoleAssignmentServiceTest.java
Previously we only used the role assignment table for authZ roles. Added the ability to add restrictions to non-authz roles.
---
- Refactored role assignment logic to also account for non-authz roles.
- Added integration tests.
- Updated unit tests.
---
=> STB-2798: Added the ability to place restrictions on non-authz roles.

src/main/java/uk/gov/justice/laa/portal/landingpage/controller/UserController.java, src/test/java/uk/gov/justice/laa/portal/landingpage/controller/UserControllerTest.java
https://dsdmoj.atlassian.net/browse/STB-2928
email check service will only verify not empty email value, the empty or null check will be handled by form validation 
---
- 
- 
- 
---
---
---
=> STB-2928 only validate non-empty email
